export const newGpuData = [
    {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "GTX 1050-Ti",
        "Rank": 129,
        "Benchmark": 31.1,
        "Samples": 840412,
        "URL": "https://gpu.userbenchmark.com/Nvidia-GTX-1050-Ti/Rating/3649",
        "id" : 1,
      },
    {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "GTX 1060-6GB",
        "Rank": 80,
        "Benchmark": 56.9,
        "Samples": 1296536,
        "URL": "https://gpu.userbenchmark.com/Nvidia-GTX-1060-6GB/Rating/3639",
        "id" : 2,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "GTX 1070",
        "Rank": 55,
        "Benchmark": 80.4,
        "Samples": 1274403,
        "URL": "https://gpu.userbenchmark.com/Nvidia-GTX-1070/Rating/3609",
        "id" : 3,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "GTX 1070-Ti",
        "Rank": 40,
        "Benchmark": 96.2,
        "Samples": 362945,
        "URL": "https://gpu.userbenchmark.com/Nvidia-GTX-1070-Ti/Rating/3943",
        "id" : 4,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "GTX 1080",
        "Rank": 32,
        "Benchmark": 106,
        "Samples": 955188,
        "URL": "https://gpu.userbenchmark.com/Nvidia-GTX-1080/Rating/3603",
        "id" : 5,
      }, 
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "GTX 1080-Ti",
        "Rank": 16,
        "Benchmark": 136,
        "Samples": 810038,
        "URL": "https://gpu.userbenchmark.com/Nvidia-GTX-1080-Ti/Rating/3918",
        "id" : 6,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "GTX 1650",
        "Rank": 102,
        "Benchmark": 43,
        "Samples": 154724,
        "URL": "https://gpu.userbenchmark.com/Nvidia-GTX-1650/Rating/4039",
        "id" : 7,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "GTX 1650S",
        "Rank": 75,
        "Benchmark": 59.9,
        "Samples": 132467,
        "URL": "https://gpu.userbenchmark.com/Nvidia-GTX-1650S-Super/Rating/4058",
        "id" : 8,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "GTX 1660",
        "Rank": 67,
        "Benchmark": 68.8,
        "Samples": 202407,
        "URL": "https://gpu.userbenchmark.com/Nvidia-GTX-1660/Rating/4038",
        "id" : 9,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "GTX 1660S",
        "Rank": 64,
        "Benchmark": 71.2,
        "Samples": 316737,
        "URL": "https://gpu.userbenchmark.com/Nvidia-GTX-1660S-Super/Rating/4056",
        "id" : 10,
      },
      {
        "Type": "GPU",
        "Part Number": "GTX 1660 TI VENTUS XS 6G OC",
        "Brand": "MSI",
        "Model": "GTX 1660 Ti",
        "Rank": 60,
        "Benchmark": 76.5,
        "Samples": 260429,
        "URL": "https://gpu.userbenchmark.com/Nvidia-GTX-1660-Ti/Rating/4037",
        "id" : 11,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "RTX 2060",
        "Rank": 49,
        "Benchmark": 88.7,
        "Samples": 527349,
        "URL": "https://gpu.userbenchmark.com/Nvidia-RTX-2060/Rating/4034",
        "id" : 12,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "RTX 2060S",
        "Rank": 37,
        "Benchmark": 99.3,
        "Samples": 286530,
        "URL": "https://gpu.userbenchmark.com/Nvidia-RTX-2060S-Super/Rating/4049",
        "id" : 13,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "RTX 2070",
        "Rank": 31,
        "Benchmark": 106,
        "Samples": 429747,
        "URL": "https://gpu.userbenchmark.com/Nvidia-RTX-2070/Rating/4029",
        "id" : 14,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "RTX 2070S",
        "Rank": 26,
        "Benchmark": 118,
        "Samples": 561715,
        "URL": "https://gpu.userbenchmark.com/Nvidia-RTX-2070S-Super/Rating/4048",
        "id" : 15,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "RTX 2080",
        "Rank": 23,
        "Benchmark": 129,
        "Samples": 293051,
        "URL": "https://gpu.userbenchmark.com/Nvidia-RTX-2080/Rating/4026",
        "id" : 16,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "RTX 2080S",
        "Rank": 15,
        "Benchmark": 137,
        "Samples": 229795,
        "URL": "https://gpu.userbenchmark.com/Nvidia-RTX-2080S-Super/Rating/4050",
        "id" : 17,
      },
      {
        "Type": "GPU",
        "Part Number": "ZT-T20810D-10P",
        "Brand": "Zotac",
        "Model": "RTX 2080 Ti",
        "Rank": 9,
        "Benchmark": 174,
        "Samples": 302277,
        "URL": "https://gpu.userbenchmark.com/Nvidia-RTX-2080-Ti/Rating/4027",
        "id" : 18,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "RTX 3060",
        "Rank": 38,
        "Benchmark": 97.8,
        "Samples": 55201,
        "URL": "https://gpu.userbenchmark.com/Nvidia-RTX-3060/Rating/4105",
        "id" : 19,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "RTX 3060-Ti",
        "Rank": 22,
        "Benchmark": 131,
        "Samples": 81687,
        "URL": "https://gpu.userbenchmark.com/Nvidia-RTX-3060-Ti/Rating/4090",
        "id" : 20,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "RTX 3070",
        "Rank": 13,
        "Benchmark": 152,
        "Samples": 305818,
        "URL": "https://gpu.userbenchmark.com/Nvidia-RTX-3070/Rating/4083",
        "id" : 21,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "RTX 3070-Ti",
        "Rank": 10,
        "Benchmark": 168,
        "Samples": 35202,
        "URL": "https://gpu.userbenchmark.com/Nvidia-RTX-3070-Ti/Rating/4116",
        "id" : 22,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "RTX 3080",
        "Rank": 4,
        "Benchmark": 204,
        "Samples": 202409,
        "URL": "https://gpu.userbenchmark.com/Nvidia-RTX-3080/Rating/4080",
        "id" : 23,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "RTX 3080-Ti",
        "Rank": 2,
        "Benchmark": 233,
        "Samples": 42788,
        "URL": "https://gpu.userbenchmark.com/Nvidia-RTX-3080-Ti/Rating/4115",
        "id" : 24,
      },
      {
        "Type": "GPU",
        "Part Number": "",
        "Brand": "Nvidia",
        "Model": "RTX 3090",
        "Rank": 1,
        "Benchmark": 234,
        "Samples": 83598,
        "URL": "https://gpu.userbenchmark.com/Nvidia-RTX-3090/Rating/4081",
        "id" : 25,
      },
]